version: '2'
services:
  redis:
    image: redis:3.0
    ports: 
      - "6379:6379"
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "4369:4369"
      - "15672:15672"
      - "5672:5672"
  mongo: 
    image: mongo:3.0
    ports:
      - "27017:27017"
  postgres:
    image: postgres:9.6
    ports: 
      - "5432:5432"
      #this is just for testing purposes
    environment:
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
   
  